r749@bastard:  jens | 2009-08-17 20:20:07 +0200  commit message also for the previous commit of blockcontrol.lib  * watchdog:    - renamed variables and files from ...watchdog to ...wd. Added special debconf transition code for this.    - trap some signals so that the watchdog can remove its own pidfile.    - improved tests of preconditional blockcontrol settings  * blockcontrol    * Fixed output to STDOUT:      - Set a trap on exit for commands with log_end_msg. Then on exit do log_end_msg. Fixes output for failed commands.      - moved test_root calls from within the functions to the head of the commands. So test_root is before writing to the logfile.      - added use of RETVAL to some commands    * status:      - make sure the return code is of the daemon (not of the watchdog).    * show_config:      - tell whether internal or system wide init-functions are used.      - tell whether start-stop-daemon is used.    * internal init-functions:      - rewritten based on Debian lsb-base 3.2-23      - use test_external for pidof. Use pidof without path. Fixes problems e.g. on Slackware      - getopts: prevent overwriting "-p pidfile" with "-p guarding.p2p"    * update:      - handle wget "access denied (403)" separately.    * get_blocklist:      - remote blocklists: test if wget is available  * removed LSB_MODE setting    - removed variable and tests    - start(_wd): use start-stop-daemon if available, otherwise LSB start_daemon, replaces Debian specific starting (LSB_MODE=0).    - for broken init-functions force to use the builtin init-functions by setting LSB=""    - TODO: use -p pidfile specification for XXXX YYYYY, but not for ZZZZZ on start/stop/status  * debian/patches:    - removed, because now obsolete
git-svn-id: https://moblock-deb.svn.sourceforge.net/svnroot/moblock-deb@438 8fc2b358-460f-0410-a19c-87dd71e10105

diff --git a/blockcontrol b/blockcontrol
--- a/blockcontrol
+++ b/blockcontrol
@@ -20,7 +20,7 @@
 # 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 
 ################################################################################
-# The following code is common between blockcontrol, blockcontrol.watchdog,
+# The following code is common between blockcontrol, blockcontrol.wd,
 # cron.daily, init and debian/postinst.
 
 # if-up is similar, but exits successfully if CONTROL_MAIN is not there, yet.
@@ -39,9 +39,28 @@ else
 	exit 7
 fi
 
-# End of the common code between blockcontrol, blockcontrol.watchdog,
+# End of the common code between blockcontrol, blockcontrol.wd,
 # cron.daily, (if-up), init and debian/postinst.
 ################################################################################
+
+RETVAL=0
+
+# Set a trap on exit for commands with log_end_msg.
+# Then on exit do log_end_msg. Fixes output for failed commands.
+case "$1" in
+	'start'|'stop'|'start_wd'|'stop_wd'|'restart'|'reload'|'force-reload'|'update'|'force-update')
+		test_root
+		# Define an exit function for trapped signals
+		onexit () {
+			RETVAL="$?"
+			[ "$VERBOSITY" -gt 0 ] && log_end_msg $RETVAL
+			exit $RETVAL
+		}
+
+		trap onexit EXIT
+		;;
+esac
+
 
 # And now, make this script usable:
 case "$1" in
@@ -61,23 +80,21 @@ case "$1" in
 		date +%F" "%X" "%Z" End: $(basename $0) $1" >> $CONTROL_LOG 2>&1
 		[ "$VERBOSITY" -gt 0 ] && log_end_msg $RETVAL
 		;;
-	'start_watchdog')
+	'start_wd')
 		test_CONTROL_LOG
-		[ "$VERBOSITY" -gt 0 ] && log_daemon_msg "Starting $CONTROL_NAME watchdog" "$CONTROL_NAME.watchdog"
+		[ "$VERBOSITY" -gt 0 ] && log_daemon_msg "Starting $CONTROL_NAME watchdog" "$(basename $WD_PATHNAME)"
 		date +%F" "%X" "%Z" Begin: $(basename $0) $1" >> $CONTROL_LOG 2>&1
-		do_start_watchdog >> $CONTROL_LOG 2>&1
+		do_start_wd >> $CONTROL_LOG 2>&1
 		date +%F" "%X" "%Z" End: $(basename $0) $1" >> $CONTROL_LOG 2>&1
 		[ "$VERBOSITY" -gt 0 ] && log_end_msg $RETVAL
-		echo ""
 		;;
-	'stop_watchdog')
+	'stop_wd')
 		test_CONTROL_LOG
-		[ "$VERBOSITY" -gt 0 ] && log_daemon_msg "Stopping $CONTROL_NAME watchdog" "$CONTROL_NAME.watchdog"
+		[ "$VERBOSITY" -gt 0 ] && log_daemon_msg "Stopping $CONTROL_NAME watchdog" "$(basename $WD_PATHNAME)"
 		date +%F" "%X" "%Z" Begin: $(basename $0) $1" >> $CONTROL_LOG 2>&1
-		do_stop_watchdog >> $CONTROL_LOG 2>&1
+		do_stop_wd >> $CONTROL_LOG 2>&1
 		date +%F" "%X" "%Z" End: $(basename $0) $1" >> $CONTROL_LOG 2>&1
 		[ "$VERBOSITY" -gt 0 ] && log_end_msg $RETVAL
-		echo ""
 		;;
 	'restart')
 		test_CONTROL_LOG
@@ -125,6 +142,13 @@ case "$1" in
 					echo "$i"
 				done
 			fi
+			if [ -n "$UPDATE_403" ] ; then
+				echo ""
+				echo "The access for the following lists was denied, but they have old usable versions:"
+				for i in $UPDATE_403 ; do
+					echo "$i"
+				done
+			fi
 			if [ -n "$UPDATE_SUCCESS_NA" ] ; then
 				echo ""
 				echo "For the following lists there was no update available:"
@@ -143,6 +167,7 @@ case "$1" in
 		fi
 		;;
 	'status')
+		test_root
 		echo "Current IPv4 iptables rules (this may take a while):"
 		echo
 		iptables -L -nv
@@ -156,14 +181,15 @@ case "$1" in
 		echo "Please check if the above printed iptables rules are correct!"
 		echo
 		status_of_proc $DAEMON $NAME
-		if [ "$?" -eq 0 ] ; then
+		RETVAL="$?"
+		if [ "$RETVAL" -eq 0 ] ; then
 			echo "PID: $(cat $PIDFILE)    CMD: $(ps -o cmd -p $(cat $PIDFILE) | tail -1)"
 			echo
 		fi
 
-		status_of_proc $WATCHDOG_PATH $(basename $WATCHDOG_PATH)
+		status_of_proc $WD_PATHNAME $(basename $WD_PATHNAME)
 		if [ "$?" -eq 0 ] ; then
-			echo "PID: $(cat $WATCHDOG_PIDFILE)    CMD: $(ps -o cmd -p $(cat $WATCHDOG_PIDFILE) | tail -1)"
+			echo "PID: $(cat $WD_PID)    CMD: $(ps -o cmd -p $(cat $WD_PID) | tail -1)"
 			echo
 		fi
 		;;
@@ -187,11 +213,25 @@ case "$1" in
 		VARIABLES="$(grep -Ev "^[[:space:]]*#" $CONTROL_DEFAULTS | grep "=" | sed "s|=.*||" | sort -u)"
 		for VAR in $VARIABLES ; do
 			eval VALUE=\$$VAR
-			# This gives the actually used value of the variable (not necessarily that which is set in CONTROL_DEFAULTS).
+			# This gives the actually used value of the variable
+			# (not necessarily that which is set in CONTROL_DEFAULTS).
 			echo ${VAR}=\"$VALUE\"
 		done
 		echo
-		[ ! -f "$LSB" ] || echo "Using $LSB."
+		if [ -f "$LSB" ] ; then
+			if head -n 1 "$LSB" | grep -q Debian > /dev/null 2>&1 ; then
+				echo "Using Debian LSB init-functions: $LSB."
+			else
+				echo "Using LSB init-functions: $LSB."
+			fi
+		else
+			echo "Using internal LSB init-functions."
+		fi
+        if test_external start-stop-daemon > /dev/null 2>&1 ; then
+            echo "Using start-stop-daemon."
+        else
+            echo "Not using start-stop-daemon."
+        fi
 		echo
 		echo "The following blocklists are configured to be used:"
 		set_LISTS_URL
@@ -201,19 +241,24 @@ case "$1" in
 		;;
 	'test')
 		test_ipblocking
+		RETVAL=$?
 		;;
 	'search')
-		[ "$#" -eq 2 ] || { echo "Usage: $(basename $0) search SEARCHPATTERN" ; exit $E_BADARGS ; }
+		[ "$#" -eq 2 ] || {
+			echo "Usage: $(basename $0) search SEARCHPATTERN"
+			exit $E_BADARGS
+			}
 		SEARCHPATTERN="$2"
 		search
+		RETVAL=$?
 		;;
 	*)
 		echo "Usage: $(basename $0) OPTION"
 		echo "Options:"
 		echo "        start"
 		echo "        stop"
-		echo "        start_watchdog"
-		echo "        stop_watchdog"
+		echo "        start_wd"
+		echo "        stop_wd"
 		echo "        restart"
 		echo "        reload"
 		echo "        update"
@@ -227,4 +272,7 @@ case "$1" in
 		exit $E_BADARGS
 		;;
 esac
+
+# Reset the trap on exit
+trap - EXIT
 exit $RETVAL
diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -60,7 +60,7 @@ esac
 
 
 ################################################################################
-# The following code is common between blockcontrol, blockcontrol.watchdog,
+# The following code is common between blockcontrol, blockcontrol.wd,
 # cron.daily, init and debian/postinst.
 
 # if-up is similar, but exits successfully if CONTROL_MAIN is not there, yet.
@@ -79,7 +79,7 @@ else
 	exit 7
 fi
 
-# End of the common code between blockcontrol, blockcontrol.watchdog,
+# End of the common code between blockcontrol, blockcontrol.wd,
 # cron.daily, (if-up), init and debian/postinst.
 ################################################################################
 
@@ -92,7 +92,7 @@ VARIABLES="
 	VERBOSITY
 	INIT
 	CRON
-	WATCHDOG
+	WD
 	NFQUEUE_NUMBER
 	IPTABLES_SETTINGS
 	IPTABLES_ACTIVATION
@@ -177,7 +177,8 @@ CONTROL_CONF="/etc/blockcontrol/blockcontrol.conf"
 CONTROL_DEFAULTS="/usr/lib/blockcontrol/blockcontrol.defaults"
 BLOCKLISTS_LIST="/etc/blockcontrol/blocklists.list"
 
-
+# Transition in blockcontrol 1.5: WATCHDOG > WD renaming
+[ -z "$WATCHDOG" ] || WD="$WATCHDOG"
 
 
 ###############################################################################
@@ -320,7 +321,7 @@ for VAR in $VARIABLES ; do
 			;;
 
 		# For boolean variables:
-		'LOG_SYSLOG'|'LOG_TIMESTAMP'|'INIT'|'CRON'|'WATCHDOG'|'REJECT'|'ACCEPT')
+		'LOG_SYSLOG'|'LOG_TIMESTAMP'|'INIT'|'CRON'|'WD'|'REJECT'|'ACCEPT')
 			case "$VALUE" in
 				'0')
 					db_set blockcontrol/$VAR false
@@ -389,7 +390,7 @@ while true ; do
 	'6')
 		db_input critical blockcontrol/INIT || true
 		db_input medium blockcontrol/CRON || true
-		db_input medium blockcontrol/WATCHDOG || true
+		db_input medium blockcontrol/WD || true
 		;;
 	'7')	# This part contains the db_go here instead of at the end of the function.
 		db_input low blockcontrol/NFQUEUE_NUMBER && RETVAL=$? || { RETVAL=$? ; true ; }
@@ -757,18 +758,18 @@ case "$RET" in
 		;;
 esac
 
-my_db_get WATCHDOG
+my_db_get WD
 case "$RET" in
 	'false')
 		if [ "$CONFFILE" = "$CONTROL_CONF" ] ; then
-			sed -i -r "s|^[[:space:]]*WATCHDOG=.*|WATCHDOG=\"0\"|" $CONTROL_CONF
+			sed -i -r "s|^[[:space:]]*WD=.*|WD=\"0\"|" $CONTROL_CONF
 		else
-			echo "WATCHDOG=\"0\"" >> $CONTROL_CONF
+			echo "WD=\"0\"" >> $CONTROL_CONF
 		fi
 		;;
 	'true')	# Default
 		if [ "$CONFFILE" = "$CONTROL_CONF" ] ; then
-			sed -i -r "s|^[[:space:]]*WATCHDOG=.*|WATCHDOG=\"1\"|" $CONTROL_CONF
+			sed -i -r "s|^[[:space:]]*WD=.*|WD=\"1\"|" $CONTROL_CONF
 		fi
 		;;
 esac
@@ -1109,7 +1110,8 @@ db_stop
 # Set the blocklist name depending on the type of the blocklist (configuration setting).
 test_set_BLOCKLIST
 
-# Move blocklists from old moblock-control places. The update path is only clean from 1.2. Lists downloaded earlier
+# Transition from moblock-control, move blocklists from old places.
+# The update path is only clean from 1.2. Lists downloaded earlier
 # will stay at their places and a new download for blockcontrol is necessary.
 if [ -d /var/lib/moblock/ ] && [ -d /var/lib/blockcontrol/ ] ; then
 	for i in ipfilter.dat guarding.p2b guarding.p2p ipfilter.dat.backup guarding.p2b.backup guarding.p2p.backup ; do
@@ -1147,12 +1149,12 @@ if [ "$INIT" -ne 0 ] && [ -x "/etc/init.d/blockcontrol" ] ; then
 	echo "process, then do in another terminal a"
 	echo " tail -f $CONTROL_LOG"
 	echo "The lists are saved to $BLOCKLISTS_DIR/."
-	echo "The installation of $CONTROL_NAME will fail, if starting $NAME fails. If this"
-	echo "happens, then in most cases downloading the blocklists failed temporarily. To"
-	echo "workaround this, you can turn the automatic starting of $NAME off by setting"
+	echo "The installation of $CONTROL_NAME will fail, if starting $NAME fails. So if"
+	echo "downloading the blocklists fails temporarily, the installation will fail."
+	echo "To workaround this, you can turn the automatic starting of $NAME off by setting"
 	echo "in $CONTROL_CONF:"
 	echo " INIT=\"0\""
-	echo
+	echo "Please be patient ..."
 fi
 
 # dh_installdeb will replace this with shell code automatically
