r310@bastard:  jens | 2009-01-17 00:41:08 +0100  moblock-control blockcontrol renaming
git-svn-id: https://moblock-deb.svn.sourceforge.net/svnroot/moblock-deb@306 8fc2b358-460f-0410-a19c-87dd71e10105

diff --git a/if-up b/if-up
--- a/if-up
+++ b/if-up
@@ -18,8 +18,8 @@
 # 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 
 ################################################################################
-# The following code is common between blockcontrol, init, cron.daily,
-# if-up and debian/postinst.
+# The following code is common between blockcontrol, cron.daily, if-up, init,
+# and debian/postinst.
 # It sets/loads the variables and functions
 
 # These two variables have to be set correctly in all just mentioned files.
@@ -33,9 +33,9 @@ STDIFS=$IFS
 # Set sane configuration defaults. They will be overwritten by the values in
 # CONTROL_CONF and CONTROL_DEFAULT
 if [ -f "$CONTROL_DEFAULTS" ] ; then
-	. $CONTROL_DEFAULTS || { echo "Error: Failed to source $CONTROL_DEFAULTS although this file exists."; exit 1; }
+	. $CONTROL_DEFAULTS || { echo "$0 Error: Failed to source $CONTROL_DEFAULTS although this file exists."; exit 1; }
 else
-	echo "Error 7: Missing file $CONTROL_DEFAULTS."
+	echo "$0 Error 7: Missing file $CONTROL_DEFAULTS."
 	exit 7
 fi
 
@@ -51,8 +51,8 @@ for PATH_I in $PATH ; do
 		DAEMON="$PATH_I/moblock"
 		DESC="MoBlock"
 		break
-	elif [ -x "$PATH_I/nfblock" ] ; then
-		NAME="nfblock"
+	elif [ -x "$PATH_I/nfblockd" ] ; then
+		NAME="nfblockd"
 		DAEMON="$PATH_I/$NAME"
 		DESC="NFblock"
 		break
@@ -62,13 +62,13 @@ IFS=$STDIFS
 
 # Load configuration. This overwrites the above values.
 if [ -f "$CONTROL_CONF" ] ; then
-	. $CONTROL_CONF || { echo "Error: Failed to source $CONTROL_CONF although this file exists."; exit 1; }
+	. $CONTROL_CONF || { echo "$0 Error: Failed to source $CONTROL_CONF although this file exists."; exit 1; }
 else
 	[ -d "$(dirname $CONTROL_CONF)" ] || {
 		echo -n "Creating missing directory $(dirname $CONTROL_CONF)"
 		mkdir "$(dirname $CONTROL_CONF)" && echo "."
 		} || {
-		log_failure_msg "Error $E_XCD: Missing directory "$(dirname $CONTROL_CONF)"."
+		log_failure_msg "$0 Error $E_XCD: Missing directory "$(dirname $CONTROL_CONF)"."
 		log_failure_msg "Check the CONTROL_CONF setting in $0."
 		exit $E_XCD
 	}
@@ -88,13 +88,13 @@ fi
 
 # Load default configuration. This overwrites the above values.
 if [ -f "$CONTROL_DEFAULT" ] ; then
-	. $CONTROL_DEFAULT || { echo "Error: Failed to source $CONTROL_DEFAULT although this file exists."; exit 1; }
+	. $CONTROL_DEFAULT || { echo "$0 Error: Failed to source $CONTROL_DEFAULT although this file exists."; exit 1; }
 else
 	[ -d "$(dirname $CONTROL_DEFAULT)" ] || {
 		echo -n "Creating missing directory $(dirname $CONTROL_DEFAULT)"
 		mkdir "$(dirname $CONTROL_DEFAULT)" && echo "."
 		} || {
-		log_failure_msg "Error $E_XCD: Missing directory "$(dirname $CONTROL_CONF)"."
+		log_failure_msg "$0 Error $E_XCD: Missing directory "$(dirname $CONTROL_CONF)"."
 		log_failure_msg "Check the CONTROL_DEFAULT setting in $0."
 		exit $E_XCD
 	}
@@ -113,24 +113,24 @@ fi
 
 # If the daemon was neither found, nore set manually, then abort now.
 if [ -z $NAME ] || [ -z $DAEMON ] || [ -z $DESC ] ; then
-	echo "Could not detect an IPBlocker daemon. MoBlock and NFBlock are supported."
+	echo "Could not detect an IPBlocker daemon. moblock and nfblockd are supported."
 	echo "Neither of them was found in PATH: $PATH."
-	echo "Error $E_CONFIG: You may set NAME, DAEMON and DESC manually in $CONTROL_CONF."
+	echo "$0 Error $E_CONFIG: You may set NAME, DAEMON and DESC manually in $CONTROL_CONF."
 	exit $E_CONFIG
 fi
 
 # Load blockcontrol library.
 if [ -f "$CONTROL_LIB" ] ; then
-	. $CONTROL_LIB || { echo "Error: Failed to source $CONTROL_LIB although this file exists."; exit 1; }
+	. $CONTROL_LIB || { echo "$0 Error: Failed to source $CONTROL_LIB although this file exists."; exit 1; }
 else
-	echo "Error $E_CONFIG: You need $CONTROL_LIB."
+	echo "$0 Error $E_CONFIG: You need $CONTROL_LIB."
 	exit $E_CONFIG
 fi
 
 load_lsb
 
-# End of the common code between blockcontrol, init, cron.daily,
-# if-up and debian/postinst.
+# End of the common code between blockcontrol, cron.daily, if-up, init,
+# and debian/postinst.
 ################################################################################
 
 if [ "$WHITE_LOCAL" -eq 1 ] && [ "$IPTABLES_SETTINGS" -eq 1 ] && daemon_status exitifstrange ; then
@@ -141,23 +141,23 @@ if [ "$WHITE_LOCAL" -eq 1 ] && [ "$IPTABLES_SETTINGS" -eq 1 ] && daemon_status e
 	for IP in $LOCAL_IPS ; do
 		case $IP in
 			127.*)	# IP is the loopback IP: If loopback device is not already whitelisted then insert whitelisting rules for whole loopback interface
-				iptables -nv -L $NAME\_in |  grep "${IPTABLES_TARGET_WHITELISTING}[[:space:]]*all[[:space:]]*--[[:space:]]*lo" > /dev/null 2>&1 || { \
-				iptables -I $NAME\_in -i lo -j $IPTABLES_TARGET_WHITELISTING || { log_end_msg $? ; exit $E_IPTABLES ; }
+				iptables -nv -L ${CONTROL_NAME}_in |  grep "${IPTABLES_TARGET_WHITELISTING}[[:space:]]*all[[:space:]]*--[[:space:]]*lo" > /dev/null 2>&1 || { \
+				iptables -I ${CONTROL_NAME}_in -i lo -j $IPTABLES_TARGET_WHITELISTING || { log_end_msg $? ; exit $E_IPTABLES ; }
 					}
-				iptables -nv -L $NAME\_out |  grep "${IPTABLES_TARGET_WHITELISTING}[[:space:]]*all[[:space:]]*--[[:space:]]*\*[[:space:]]*lo" > /dev/null 2>&1 || { \
-					iptables -I $NAME\_out -o lo -j $IPTABLES_TARGET_WHITELISTING || { log_end_msg $? ; exit $E_IPTABLES ; }
+				iptables -nv -L ${CONTROL_NAME}_out |  grep "${IPTABLES_TARGET_WHITELISTING}[[:space:]]*all[[:space:]]*--[[:space:]]*\*[[:space:]]*lo" > /dev/null 2>&1 || { \
+					iptables -I ${CONTROL_NAME}_out -o lo -j $IPTABLES_TARGET_WHITELISTING || { log_end_msg $? ; exit $E_IPTABLES ; }
 					}
 				;;
 			*)	# If the LAN is not already whitelisted then insert whitelisting rules for LAN (IP with subnetmask /24)
-				iptables -nv -L $NAME\_in | grep ${IP}0/24  > /dev/null 2>&1 || { \
-					iptables -I $NAME\_in --source ${IP}0/24 -j $IPTABLES_TARGET_WHITELISTING || { log_end_msg $? ; exit $E_IPTABLES ; }
+				iptables -nv -L ${CONTROL_NAME}_in | grep ${IP}0/24  > /dev/null 2>&1 || { \
+					iptables -I ${CONTROL_NAME}_in --source ${IP}0/24 -j $IPTABLES_TARGET_WHITELISTING || { log_end_msg $? ; exit $E_IPTABLES ; }
 					}
-				iptables -nv -L $NAME\_out | grep ${IP}0/24  > /dev/null 2>&1 || { \
-					iptables -I $NAME\_out --destination ${IP}0/24 -j $IPTABLES_TARGET_WHITELISTING || { log_end_msg $? ; exit $E_IPTABLES ; }
+				iptables -nv -L ${CONTROL_NAME}_out | grep ${IP}0/24  > /dev/null 2>&1 || { \
+					iptables -I ${CONTROL_NAME}_out --destination ${IP}0/24 -j $IPTABLES_TARGET_WHITELISTING || { log_end_msg $? ; exit $E_IPTABLES ; }
 					}
-				iptables -nv -L $NAME\_fw | grep ${IP}0/24  > /dev/null 2>&1 || { \
-					iptables -I $NAME\_fw --source ${IP}0/24 -j $IPTABLES_TARGET_WHITELISTING || { log_end_msg $? ; exit $E_IPTABLES ; }
-					iptables -I $NAME\_fw --destination ${IP}0/24 -j $IPTABLES_TARGET_WHITELISTING || { log_end_msg $? ; exit $E_IPTABLES ; }
+				iptables -nv -L ${CONTROL_NAME}_fw | grep ${IP}0/24  > /dev/null 2>&1 || { \
+					iptables -I ${CONTROL_NAME}_fw --source ${IP}0/24 -j $IPTABLES_TARGET_WHITELISTING || { log_end_msg $? ; exit $E_IPTABLES ; }
+					iptables -I ${CONTROL_NAME}_fw --destination ${IP}0/24 -j $IPTABLES_TARGET_WHITELISTING || { log_end_msg $? ; exit $E_IPTABLES ; }
 					}
 				;;
 		esac
