r515@bastard:  jens | 2009-08-31 19:27:54 +0200  Cleanup whitespace:  sed -i -r "s|\t|    |g" $FILE  sed -i -r "s|[[:space:]]*$||g" $FILE
git-svn-id: https://moblock-deb.svn.sourceforge.net/svnroot/moblock-deb@456 8fc2b358-460f-0410-a19c-87dd71e10105

diff --git a/init b/init
--- a/init
+++ b/init
@@ -27,11 +27,11 @@
 # Default-Stop:      0 1 6
 # Short-Description: IP block daemon initscript
 # Description:       An IP blocker for Linux
-#	MoBlock blocks connections from/to hosts listed in a very large blocklist.
-#	The blocklist can be in one of the following formats: eMule "ipfilter.dat",
-#	"peerguardian .p2p text" or "peerguardian .p2b v2 binary".
-#	This package uses the xt_NFQUEUE kernel module (available since kernel
-#	>=2.6.13).
+#    MoBlock blocks connections from/to hosts listed in a very large blocklist.
+#    The blocklist can be in one of the following formats: eMule "ipfilter.dat",
+#    "peerguardian .p2p text" or "peerguardian .p2b v2 binary".
+#    This package uses the xt_NFQUEUE kernel module (available since kernel
+#    >=2.6.13).
 ### END INIT INFO
 
 ################################################################################
@@ -48,10 +48,10 @@ CONTROL_MAIN="/usr/lib/blockcontrol/blockcontrol.main"
 
 # Configure blockcontrol and load functions.
 if [ -f "$CONTROL_MAIN" ] ; then
-	. $CONTROL_MAIN || { echo "$0 Error: Failed to source $CONTROL_MAIN although this file exists."; exit 1; }
+    . $CONTROL_MAIN || { echo "$0 Error: Failed to source $CONTROL_MAIN although this file exists."; exit 1; }
 else
-	echo "$0 Error 7: Missing file $CONTROL_MAIN."
-	exit 7
+    echo "$0 Error 7: Missing file $CONTROL_MAIN."
+    exit 7
 fi
 
 # End of the common code between blockcontrol, blockcontrol.wd,
@@ -63,30 +63,30 @@ test_VERBOSITY
 test_CONTROL_SCRIPT
 
 case "$1" in
-	start)
-		case "$INIT" in
-			# Automatic boot is off:
-			0)
-				if [ "$VERBOSITY" -eq 1 ] ; then
-					log_warning_msg "$(basename $0) is configured not to start automatically at boot time."
-					log_warning_msg "To change this edit the INIT entry in $CONTROL_CONF."
-					log_warning_msg "If you don't want to see this message set VERBOSITY=\"2\" there."
-				fi
-				exit 0
-				;;
-			# Automatic boot is on:
-			1)
-				$CONTROL_SCRIPT $1
-				;;
-		esac
-		;;
-	stop|restart|reload|force-reload|update|status)
-		$CONTROL_SCRIPT $1
-		;;
-	*)
-		log_warning_msg "Usage: $0 {start|stop|restart|reload|update|status}"
-		exit $E_BADARGS
-		;;
+    start)
+        case "$INIT" in
+            # Automatic boot is off:
+            0)
+                if [ "$VERBOSITY" -eq 1 ] ; then
+                    log_warning_msg "$(basename $0) is configured not to start automatically at boot time."
+                    log_warning_msg "To change this edit the INIT entry in $CONTROL_CONF."
+                    log_warning_msg "If you don't want to see this message set VERBOSITY=\"2\" there."
+                fi
+                exit 0
+                ;;
+            # Automatic boot is on:
+            1)
+                $CONTROL_SCRIPT $1
+                ;;
+        esac
+        ;;
+    stop|restart|reload|force-reload|update|status)
+        $CONTROL_SCRIPT $1
+        ;;
+    *)
+        log_warning_msg "Usage: $0 {start|stop|restart|reload|update|status}"
+        exit $E_BADARGS
+        ;;
 esac
 
 exit $?
