pglcmd: Move the builtin LSB init-functions to a separate file.
Load the new pglcmd.lsb.lib from pglcmd.main.
Define its pathname as LSB_BUILTIN in pglcmd.defaults.

diff --git a/pglcmd/pglcmd.main.in b/pglcmd/pglcmd.main.in
--- a/pglcmd/pglcmd.main.in
+++ b/pglcmd/pglcmd.main.in
@@ -39,17 +39,22 @@ if [ -f "$CMD_CONF" ] ; then
     . $CMD_CONF || echo "$0 Warning: Failed to source $CMD_CONF although this file exists."
 fi
 
+# Load fallback LSB init-functions shell library.
+# Those functions will be overwritten by the system's LSB init-functions
+# (if $LSB provides the used functions).
+if [ -f "$LSB_BUILTIN" ] ; then
+    . "$LSB_BUILTIN" || echo "$0 Warning: Failed to source ${LSB_BUILTIN} although this file exists."
+fi
+
+# Load LSB init-functions shell library
+if [ -f "$LSB" ] ; then
+    . "$LSB" || echo "$0 Warning: Failed to source $LSB although this file exists."
+fi
+
 # Load pglcmd library.
 if [ -f "$CMD_LIB" ] ; then
     . $CMD_LIB || { echo "$0 Error: Failed to source $CMD_LIB although this file exists."; exit 1; }
 else
     echo "$0: Missing file $CMD_LIB (Error $E_XFILE)."
     exit $E_XFILE
-fi
-
-# Load LSB init-functions shell library
-# As fallback there's a modified copy of the Debian init-functions in
-# pglcmd.lib. Those functions will be overwritten by the following functions.
-if [ -f "$LSB" ] ; then
-    . $LSB || echo "$0 Warning: Failed to source $LSB although this file exists."
 fi
